### ISSUE TITLE
[emacs] 放置 issue を消化する

### ISSUE THREAD

**Issue by zk-phi** [zk-phi/dotfiles#19]

**Comment by zk-phi** [comment]
[indent-guide]
- recursive 関連
  - [ ] (中) https://github.com/zk-phi/indent-guide/issues/40 なんか死ぬ

[phi-search]
- [ ] (低) https://github.com/zk-phi/phi-search/issues/49 search history 実装して

[sublimity]
- [ ] (低) https://github.com/zk-phi/sublimity/issues/33 hscroll の挙動が Circe で使うとき不便

[magic-latex-buffers]
- [ ] (低) https://github.com/zk-phi/magic-latex-buffer/issues/22 org-mode でも数式をかっこよくして
- [ ] (中) https://github.com/zk-phi/magic-latex-buffer/issues/20 クッソ重い
- [ ] (低) https://github.com/zk-phi/magic-latex-buffer/issues/18 `\textsuperscript` をサポートして

[scad-preview]
- [ ] (中) https://github.com/zk-phi/scad-preview/issues/1 一時ファイルが一瞬で消えてプレビューされない

**Comment by zk-phi** [comment]
優先度高

- commentize-conflict
  - [ ] (高) https://github.com/zk-phi/commentize-conflict/issues/6 web-mode 対応

**Comment by zk-phi** [comment]
優先度中

- sublimity
  - map 関連
    - [ ] (中) https://github.com/zk-phi/sublimity/issues/3 clickable minimap
    - [ ] (中) https://github.com/zk-phi/sublimity/issues/24 一部のウィンドウには map 出したくない
  - distraction free mode
    - [ ] (中) https://github.com/zk-phi/sublimity/issues/26 fringe が地の果てに行ってしまう
    - [ ] (中) https://github.com/zk-phi/sublimity/issues/22 linum と併用するとマージンがついたり消えたり
  - smooth scroll
    - [ ] (中) https://github.com/zk-phi/sublimity/issues/21 company と併用すると勝手にスクロールする

- togetherly
  - [ ] (中) https://github.com/zk-phi/togetherly/issues/3 multiple instances
  - [ ] (中) https://github.com/zk-phi/togetherly/issues/2 コマンドを追加できる API

- symon
  - [ ] (中) https://github.com/zk-phi/symon/issues/31 なんらかの事情で描画されない
  - [ ] (中) https://github.com/zk-phi/symon/issues/20 mac かつ fish だと動かない

- magic-latex-buffers
  - [ ] (中) https://github.com/zk-phi/magic-latex-buffer/issues/20 クッソ重い問題

- indent-guide
  - recursive 関連
    - [ ] (中) https://github.com/zk-phi/indent-guide/issues/40 なんか死にます
    - [ ] (中) https://github.com/zk-phi/indent-guide/issues/47 js2-mode で死ぬ
  - [ ] (中) https://github.com/zk-phi/indent-guide/issues/42 vimish-fold と一緒に使いたい
  - [ ] (中) https://github.com/zk-phi/indent-guide/issues/32 popup がガタガタになる

- cedit
  - [ ] (中) https://github.com/zk-phi/cedit/pull/5 fork しましたよー

- electric-align
  - [ ] (中) https://github.com/zk-phi/electric-align/issues/1 abbrev 類が動かなくなる

- scad-preview
  - [ ] (中) https://github.com/zk-phi/scad-preview/issues/1 一時ファイルが一瞬で消えてプレビューされない

- phi-search
  - [ ] (中) https://github.com/zk-phi/phi-search/issues/24 mode-line 更新されない
  - [ ] (中) https://github.com/zk-phi/phi-search/issues/42 phi-search--active がリセットされない場合がある
  - [ ] (中) https://github.com/zk-phi/phi-search/issues/40 search 中に read-from-minibufer すると壊れる
  - [ ] (中) https://github.com/zk-phi/phi-search/issues/36 idle delay 入れてぴょんぴょんしないようにする
  - [ ] (中) https://github.com/zk-phi/phi-search/issues/49 search history 実装してほしい

**Comment by zk-phi** [comment]
優先度低

- togetherly
  - [ ] (低) https://github.com/zk-phi/togetherly/issues/1 togetherly バッファを保存できない

- sublimity
  - map 関連
    - [ ] (低) https://github.com/zk-phi/sublimity/issues/35 margin が設定されてるとなんか変
    - [ ] (低) https://github.com/zk-phi/sublimity/issues/9 truncate-lines がうまくいかない
  - smooth scroll
    - [ ] (低) https://github.com/zk-phi/sublimity/issues/11 vim の smooth_scroll はいいぞ
    - [ ] (低) https://github.com/zk-phi/sublimity/issues/33 hscroll の挙動が Circe とマッチしない

- chillized-theme
  - [ ] (低) https://github.com/zk-phi/chillized-theme/issues/1 MELPA に出してほしい

- magic-latex-buffers
  - [ ] (低) https://github.com/zk-phi/magic-latex-buffer/issues/24 シンボルを動的に追加したい
  - [ ] (低) https://github.com/zk-phi/magic-latex-buffer/issues/2 auto-complete やや壊れる
  - [ ] (低) https://github.com/zk-phi/magic-latex-buffer/issues/22 org-mode でも数式をかっこよくして
  - [ ] (低) https://github.com/zk-phi/magic-latex-buffer/issues/18 `\textsuperscript` をサポートして

- indent-guide
  - recursive 関連
    - [ ] (低) https://github.com/zk-phi/indent-guide/issues/25 なんか壊れました
  - [ ] (低) https://github.com/zk-phi/indent-guide/issues/35 fci と併用するとやや壊れる
  - [ ] (低) https://github.com/zk-phi/indent-guide/issues/31 レベルごとに face を変える

- cedit
  - [ ] (低) https://github.com/zk-phi/cedit/issues/4 ファイルの内容によっては？壊れる

- phi-search
  - [ ] (低) https://github.com/zk-phi/phi-search/issues/33 ミスマッチ時のクエリのハイライトを良くする
    - 少なくとも search history が先（たぶん利用できる）

**Comment by zk-phi** [comment]
ぱっとできそう

- sublimity-map とか indent-guide の recursive を EXPERIMENTAL, NOT RECOMENDED にしよう

- https://github.com/zk-phi/lenlen-theme/pull/2 load-theme に対応しましたよ
- https://github.com/zk-phi/symon/issues/25 zero-division 直しました

返事がないのでいったん閉じでよさそう

- https://github.com/zk-phi/symon/pull/21
- https://github.com/zk-phi/sublimity/issues/31
- https://github.com/zk-phi/magic-latex-buffer/issues/13
- https://github.com/zk-phi/sublimity/issues/19
- https://github.com/zk-phi/spray/issues/6 ian さんに渡したので
- https://github.com/zk-phi/sublimity/issues/14
